### ISSUE TITLE
Enhancement for your profile page

### ISSUE THREAD

**Issue by christoph-fricke** [olafur-andri/olafur-andri.github.io#1]
It would be nice if the language container (the dropdown where the user can change the language) closes if you click somewhere on the page. That would be a much better UX experience instead of clicking on the icon again as the only option.

You can achieve this with a full `page wrapper` which gets displayed when the `container` is visible and is of course transparent. Just add a simple `EventListener` to it to close the container `onclick`. Feel free to take a look at the codebase for my website if you are wondering how it is done.

Nice website by the way... 😉

**Comment by olafur-andri** [comment]
Thank you, Christoph for your feedback! I will definitely look into this as
soon as I can. I'll make sure to check out your website for reference.
